---
- name: Install Python
  import_tasks: python.yml
- name: Project user and group
  user:
    name: "{{ project_user }}"
    group: "{{ nginx_group }}"
    state: present
- name: Virtualenv Setup
  import_tasks: virtualenv.yml
- name: Setup Project
  block:
    - name: Setup the Git repo
      git:
        repo: "{{ git_repo }}"
        version: "{{ git_branch }}"
        dest: "{{ project_path }}"
        accept_hostkey: yes
        force: yes
      notify: restart application
      changed_when: False
      tags:
        - git
        - deploy
    - name: Delete all .pyc files
      command: find . -name '*.pyc' -delete
      args:
        chdir: "{{ project_path }}"
      changed_when: False
      tags: deploy
    - name: Install pip requirements
      pip:
        virtualenv: "{{ virtualenv_path }}"
        virtualenv_python: "{{ python_exe }}"
        requirements: "{{ project_path }}/requirements.txt"
      notify: restart application
      tags:
        - deploy
        - packages
- name: Supervisord Setup
  import_tasks: supervisor.yml
- name: Set Permissions
  file:
    dest: "{{ project_path }}"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    recurse: yes
  changed_when: False
  tags:
    - deploy
- name: Set manage.py permissions
  file:
    dest: "{{ project_path }}/manage.py"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: "754"
  changed_when: False
  tags:
    - deploy
- name: Final manipulations
  block:
    - name: Run database migrations
      django_manage:
        command: migrate
        app_path: "{{ project_path }}"
        virtualenv: "{{ virtualenv_path }}"
        settings: "{{ django_environment.DJANGO_SETTINGS_MODULE }}"
      environment: "{{ django_environment }}"
      tags:
        - deploy
        - migrate
    - name: Run collectstatic
      django_manage:
        command: collectstatic
        app_path: "{{ project_path }}"
        virtualenv: "{{ virtualenv_path }}"
        settings: "{{ django_environment.DJANGO_SETTINGS_MODULE }}"
      environment: "{{ django_environment }}"
      changed_when: False
      tags:
        - deploy
        - collectstatic
