---
- unarchive:
    src: "{{ python_download_url }}"
    dest: /tmp/
    remote_src: yes
    creates: "{{ python_tmp_path }}"
  tags: python
- package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-apt
    - python3-dev
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev
    - liblzma-dev
    - python-openssl
    - openssl
    - git
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - libc6-dev
    - libgdbm-dev
    - xz-utils
    - tk-dev
    - gettext
    - libgettextpo-dev
  tags:
    - packages
    - python
- stat:
    path: "{{ python_exec_path }}"
  register: python_installed
  tags:
    - python
- command: "{{ item }}"
  become: true
  args:
    chdir: "{{ python_tmp_path }}"
  with_items:
    - "./configure --enable-optimizations"
    - "make -d"
    - make install
  when: not python_installed.stat.exists
  ignore_errors: true
  tags:
    - python
- stat:
    path: "{{ pip_exec_path }}"
  register: pip_installed
  tags:
    - python
- name: Download get-pip script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "{{ python_tmp_path }}/get-pip.py"
  when: not pip_installed.stat.exists
  tags:
    - python
- name: Install pip
  command: "{{ python_exec_path }} {{ python_tmp_path }}/get-pip.py"
  when: not pip_installed.stat.exists
  tags:
    - python
- package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"
  when: additional_packages is defined
  tags: packages
