---
- name: Supervisord Install
  package:
    name: supervisor
    state: present
  tags: packages
- name: Setup Log Directory
  file:
    path: "{{ application_log_dir }}"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0774
    state: directory
- name: Create or Retain Log File
  copy:
    content: ""
    dest: "{{ application_log_file }}"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0664
    force: no
- name: Supervisord Conf
  template:
    src: supervisor_conf.j2
    dest: "/etc/supervisor/conf.d/{{ project_name }}.conf"
    backup: yes
  notify: restart application
- name: Supervisord Service
  service:
    name: supervisor
    state: started
    enabled: yes
