---
- name: DJANGO | Supervisord Install
  package:
    name: supervisor
    state: present
  tags: packages
- name: DJANGO | Supervisord Service
  service:
    name: supervisor
    state: started
    enabled: yes
- name: DJANGO | Supervisord Conf
  template:
    src: supervisor_conf.j2
    dest: "/etc/supervisor/conf.d/{{ project_name }}.conf"
    backup: yes
  notify: restart application
- name: DJANGO | Re-read Supervisor conf files
  supervisorctl:
    name: "{{ project_name }}"
    state: present