---
- name: DJANGO | UWSGI ini template
  template:
    src: project_ini.j2
    dest: "{{ virtualenv_path }}/{{ project_name }}.ini"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    backup: yes
  notify: restart application
- name: DJANGO | UWSGI script
  template:
    src: run_uwsgi.j2
    dest: "{{ virtualenv_path }}/bin/run_uwsgi"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    backup: yes
  notify: restart application
- name: DJANGO | Setup Log Directory
  file:
    path: "{{ application_log_dir }}"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0774
    state: directory
- name: DJANGO | Create or Retain Log File
  copy:
    content: ""
    dest: "{{ application_log_file }}"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0664
    force: no
- name: DJANGO | Install UWSGI
  pip:
    name: uwsgi
    state: latest
    virtualenv: "{{ virtualenv_path }}"
  tags:
    - deploy
    - packages
- name: DJANGO | Make sure socket exists
  file:
    path: "/tmp/{{ project_name }}.sock"
    owner: "{{ project_user }}"
    group: "{{ nginx_group }}"
    mode: 0664
    state: touch
  changed_when: false