---
- name: Ensure Projects Root Exists
  file:
    path: "{{ projects_root }}"
    state: directory
- name: Install Virtualenv
  pip:
    name: virtualenv
- name: Create Virtualenv
  command: virtualenv -p {{ python_exec_path }} {{ virtualenv_path }}
  args:
    creates: "{{ virtualenv_path }}/bin/activate"
