---
- name: Ensure Projects Root Exists
  file:
    path: "{{ projects_root }}"
    state: directory
- name: Install Virtualenv
  command: "{{ python_exec_path }} {{ pip_exec_path }} install virtualenv"
  become: true
- name: Create Virtualenv
  command: virtualenv -p {{ python_exec_path }} {{ virtualenv_path }}
  args:
    creates: "{{ virtualenv_path }}/bin/activate"
