---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: jrei/systemd-ubuntu:18.04
    dockerfile: Dockerfile.j2
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
